<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Conexao' => $baseDir . '/model/Conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
);
