<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit49be9c97333e409d8a4951e93843ca7a
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Carrinho' => __DIR__ . '/../..' . '/model/Carrinho.class.php',
        'Clientes' => __DIR__ . '/../..' . '/model/Cliente.class.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Conexao' => __DIR__ . '/../..' . '/model/Conexao.class.php',
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Configuracoes' => __DIR__ . '/../..' . '/model/Configuracoes.class.php',
        'Imagens' => __DIR__ . '/../..' . '/model/Imagens.class.php',
        'Login' => __DIR__ . '/../..' . '/model/Login.class.php',
        'Menu' => __DIR__ . '/../..' . '/model/Menu.class.php',
        'Paginacao' => __DIR__ . '/../..' . '/model/Paginacao.class.php',
        'Produto' => __DIR__ . '/../..' . '/model/Produto.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'Sistema' => __DIR__ . '/../..' . '/model/Sistema.class.php',
        'Smarty' => __DIR__ . '/..' . '/smarty/smarty/libs/Smarty.class.php',
        'SmartyBC' => __DIR__ . '/..' . '/smarty/smarty/libs/SmartyBC.class.php',
        'SmartyCompilerException' => __DIR__ . '/..' . '/smarty/smarty/libs/Smarty.class.php',
        'SmartyException' => __DIR__ . '/..' . '/smarty/smarty/libs/Smarty.class.php',
        'Smarty_Security' => __DIR__ . '/..' . '/smarty/smarty/libs/sysplugins/smarty_security.php',
        'Template' => __DIR__ . '/../..' . '/model/Template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit49be9c97333e409d8a4951e93843ca7a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit49be9c97333e409d8a4951e93843ca7a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit49be9c97333e409d8a4951e93843ca7a::$classMap;

        }, null, ClassLoader::class);
    }
}
